server:
  port: 8080

  datasource:
    driveClassName: org.postgresql.Driver
    driver-class-name: org.postgresql.Driver
    password: dbPass1234@
    url: jdbc:postgresql://localhost:5432/dcbapp
    username: general
  jpa:
    hibernate:
      ddl-auto: update
welcome:
  message: Welcome to Tyagi's Project!

